### ISSUE TITLE
Nuxt Run Generate Gives Error window is not defined

### ISSUE THREAD

**Issue by ghost** [domarpdev/domarpdev.github.io#2]
Hi there,

Thanks for building this amazing tool.

I've raised this error.
https://stackoverflow.com/questions/64371120/nuxt-run-generate-gives-error-window-is-not-defined

Basically i want to host the app on firebase and i run npm run build, but i got an error
```
ERROR  window is not defined                                                                                                                14:40:27

  at a.setWidths (pages/index.js:2254:7)
  at un.run (node_modules/vue/dist/vue.runtime.common.prod.js:6:27543)
  at sn (node_modules/vue/dist/vue.runtime.common.prod.js:6:25554)
  at Array.<anonymous> (node_modules/vue/dist/vue.runtime.common.prod.js:6:12260)
  at Wt (node_modules/vue/dist/vue.runtime.common.prod.js:6:11661)
```

And i don't know also from where this error comes.
if you can help me, I would owe you a lot!

PS How do you build/generate this site in firebase?
Thank you!

**Comment by Pramod-Devireddy** [comment]
Hi, did you get the mentioned error with this project or your personal project?
I see that the `nuxt.config.js `  contents mentioned in your StackOverflow question are not from this project. Please close the issue if it is not relevant to this project.

Anyway, I will try to help you. The mentioned error occurs if you are using `window` somewhere in your code. `window` is only available in browsers and `Node JS` doesn't know about `window`. I hope you have the same issue as here: https://stackoverflow.com/questions/54979644/window-is-not-defined-in-nuxt-js

> PS How do you build/generate this site in firebase?

Do you mean how to use firebase to host a nuxt app?
Then, you can follow this video https://www.youtube.com/watch?v=w7xKZ5PWizs 
It is very simple once you generate static files by `nuxt generate` it is exactly similar to any other static site.
Or if you want to use firebase for other features like auth, firestore, functions, realtimeDB etc. then nuxt community has developed an awesome module for firebase: https://firebase.nuxtjs.org/

**Comment by ghost** [comment]
Thank you! It solved by itself!

**Comment by AimeSoleil** [comment]
> Thank you! It solved by itself!

@cohen-ro Would you pls share the solution? I've been sufferring same issue
